"use client";

import { useState } from "react";
import { skills } from "@/lib/api";
import { Button } from "@/components/ui/button";

interface ApplicationWriterModalProps {
  jobId: string;
  jobTitle: string;
  jobCompany: string;
  onClose: () => void;
  onSuccess: (applicationId: string) => void;
}

export function ApplicationWriterModal({
  jobId,
  jobTitle,
  jobCompany,
  onClose,
  onSuccess,
}: ApplicationWriterModalProps) {
  const [step, setStep] = useState<"idle" | "generating" | "review" | "submitting" | "done">("idle");
  const [coverLetter, setCoverLetter] = useState("");
  const [source, setSource] = useState<"ai" | "template" | null>(null);
  const [error, setError] = useState<string | null>(null);

  async function handleGenerate() {
    setStep("generating");
    setError(null);
    try {
      const result = await skills.generateCoverLetter({ jobId });
      setCoverLetter(result.coverLetter);
      setSource(result.source);
      setStep("review");
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to generate cover letter");
      setStep("idle");
    }
  }

  async function handleSubmit() {
    setStep("submitting");
    setError(null);
    try {
      const result = await skills.submitApplication({ jobId, coverLetter });
      setStep("done");
      onSuccess(result.application.id);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to submit application");
      setStep("review");
    }
  }

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 px-4"
      role="dialog"
      aria-modal="true"
      aria-label="Application Writer"
    >
      <div className="bg-white rounded-lg shadow-xl w-full max-w-2xl max-h-[90vh] overflow-y-auto">
        <div className="flex items-center justify-between p-5 border-b border-gray-100">
          <div>
            <h2 className="text-lg font-semibold text-gray-900">Apply with AI</h2>
            <p className="text-sm text-gray-500 mt-0.5">
              {jobTitle} at {jobCompany}
            </p>
          </div>
          <button
            onClick={onClose}
            aria-label="Close modal"
            className="text-gray-400 hover:text-gray-600 text-xl leading-none"
          >
            ×
          </button>
        </div>

        <div className="p-5 space-y-4">
          {error && (
            <div className="rounded-md bg-red-50 border border-red-200 p-3 text-sm text-red-700">
              {error}
            </div>
          )}

          {step === "done" && (
            <div className="text-center py-8">
              <p className="text-lg font-semibold text-green-700">Application Submitted!</p>
              <p className="text-sm text-gray-500 mt-1">
                Your application to {jobCompany} has been sent.
              </p>
              <Button onClick={onClose} className="mt-4">
                Close
              </Button>
            </div>
          )}

          {step === "idle" && (
            <div className="text-center py-6 space-y-4">
              <p className="text-sm text-gray-600">
                Claude will generate a personalised cover letter using your saved resume and this job description.
                You can review and edit it before submitting.
              </p>
              <Button onClick={handleGenerate} data-testid="generate-cover-letter-btn">
                Generate Cover Letter
              </Button>
            </div>
          )}

          {step === "generating" && (
            <div className="text-center py-8">
              <p className="text-sm text-gray-500">Writing your cover letter with Claude...</p>
            </div>
          )}

          {(step === "review" || step === "submitting") && (
            <>
              {source && (
                <div className="flex items-center gap-2">
                  <span className="text-xs text-gray-400">
                    {source === "ai" ? "Generated by Claude" : "Template (AI unavailable)"}
                  </span>
                </div>
              )}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Cover Letter <span className="text-gray-400 font-normal">(editable)</span>
                </label>
                <textarea
                  value={coverLetter}
                  onChange={(e) => setCoverLetter(e.target.value)}
                  rows={12}
                  data-testid="cover-letter-textarea"
                  className="w-full rounded-md border border-gray-300 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 resize-none"
                />
              </div>
              <div className="flex gap-3 pt-2">
                <Button
                  onClick={handleGenerate}
                  disabled={step === "submitting"}
                  className="border border-gray-300 bg-white text-gray-700 hover:bg-gray-50"
                >
                  Regenerate
                </Button>
                <Button
                  onClick={handleSubmit}
                  disabled={step === "submitting" || !coverLetter.trim()}
                  data-testid="submit-application-btn"
                  className="flex-1"
                >
                  {step === "submitting" ? "Submitting..." : "Submit Application"}
                </Button>
              </div>
            </>
          )}
        </div>
      </div>
    </div>
  );
}
