import { FeatureItem } from "./plan-card";

// Candidate plan definitions
export const CANDIDATE_PLANS = [
  {
    key: "FREE",
    name: "Free",
    description: "Start your job search",
    popular: false,
    features: [
      { label: "Browse all jobs", included: "yes" },
      { label: "Applications", included: "limited", limit: "5/month" },
      { label: "Basic profile", included: "yes" },
      { label: "Saved searches", included: "limited", limit: "3" },
      { label: "Job alerts", included: "yes" },
      { label: "AI resume review", included: "no" },
      { label: "AI auto-apply", included: "no" },
      { label: "AI chatbot", included: "no" },
      { label: "Priority matching", included: "no" },
      { label: "Resume tailoring", included: "no" },
      { label: "Skills assessments", included: "no" },
    ] as FeatureItem[],
  },
  {
    key: "BASIC",
    name: "Basic",
    description: "Supercharge your search",
    popular: false,
    features: [
      { label: "Browse all jobs", included: "yes" },
      { label: "Unlimited applications", included: "yes" },
      { label: "Enhanced profile", included: "yes" },
      { label: "Unlimited saved searches", included: "yes" },
      { label: "Job alerts", included: "yes" },
      { label: "AI resume review", included: "limited", limit: "10/month" },
      { label: "Salary reports", included: "yes" },
      { label: "AI auto-apply", included: "no" },
      { label: "AI chatbot", included: "yes" },
      { label: "Priority matching", included: "no" },
      { label: "Resume tailoring", included: "no" },
    ] as FeatureItem[],
  },
  {
    key: "PROFESSIONAL",
    name: "Professional",
    description: "Let AI work for you",
    popular: true,
    features: [
      { label: "Everything in Basic", included: "yes" },
      { label: "Unlimited AI resume reviews", included: "yes" },
      { label: "AI job matching", included: "limited", limit: "20/month" },
      { label: "AI apply packs", included: "limited", limit: "5/month" },
      { label: "AI auto-apply (Autopilot)", included: "yes" },
      { label: "AI chatbot (advanced)", included: "yes" },
      { label: "Priority matching", included: "yes" },
      { label: "Resume tailoring", included: "yes" },
      { label: "Skills assessments", included: "yes" },
      { label: "Priority support", included: "yes" },
    ] as FeatureItem[],
  },
];

export const EMPLOYER_PLANS = [
  {
    key: "EMPLOYER_FREE",
    name: "Employer Free",
    description: "Try hiring on AfriTalent",
    popular: false,
    features: [
      { label: "Unlimited job postings", included: "yes" },
      { label: "Applicant management", included: "yes" },
      { label: "Company profile", included: "yes" },
      { label: "Candidate search", included: "no" },
      { label: "Analytics dashboard", included: "no" },
      { label: "AI candidate ranking", included: "no" },
      { label: "ATS integration", included: "no" },
      { label: "API access", included: "no" },
      { label: "Priority support", included: "no" },
    ] as FeatureItem[],
  },
  {
    key: "EMPLOYER_BASIC",
    name: "Employer Basic",
    description: "Scale your hiring",
    popular: false,
    features: [
      { label: "Unlimited job postings", included: "yes" },
      { label: "Applicant management", included: "yes" },
      { label: "Company profile", included: "yes" },
      { label: "Candidate search", included: "yes" },
      { label: "Analytics dashboard", included: "yes" },
      { label: "AI candidate ranking", included: "no" },
      { label: "ATS integration", included: "no" },
      { label: "API access", included: "no" },
      { label: "Priority support", included: "no" },
    ] as FeatureItem[],
  },
  {
    key: "EMPLOYER_PREMIUM",
    name: "Employer Premium",
    description: "Full-power recruiting",
    popular: true,
    features: [
      { label: "Unlimited job postings", included: "yes" },
      { label: "Applicant management", included: "yes" },
      { label: "Verified company profile", included: "yes" },
      { label: "Candidate search", included: "yes" },
      { label: "Advanced analytics", included: "yes" },
      { label: "AI candidate ranking", included: "yes" },
      { label: "ATS integration", included: "yes" },
      { label: "API access", included: "yes" },
      { label: "Priority support", included: "yes" },
    ] as FeatureItem[],
  },
];

// Comparison table data
export const CANDIDATE_COMPARISON_ROWS = [
  { feature: "Job browsing", values: { Free: true, Basic: true, Professional: true } },
  { feature: "Applications per month", values: { Free: "5", Basic: "Unlimited", Professional: "Unlimited" } },
  { feature: "Saved searches", values: { Free: "3", Basic: "Unlimited", Professional: "Unlimited" } },
  { feature: "Job alerts", values: { Free: true, Basic: true, Professional: true } },
  { feature: "AI resume review", values: { Free: false, Basic: "10/mo", Professional: "Unlimited" } },
  { feature: "AI chatbot", tooltip: "Personal AI assistant for job search guidance", values: { Free: false, Basic: true, Professional: true } },
  { feature: "Salary reports access", values: { Free: false, Basic: true, Professional: true } },
  { feature: "AI job matching", tooltip: "AI finds and scores jobs for you", values: { Free: false, Basic: false, Professional: "20/mo" } },
  { feature: "AI apply packs", tooltip: "AI generates tailored resumes and cover letters", values: { Free: false, Basic: false, Professional: "5/mo" } },
  { feature: "AI auto-apply (Autopilot)", tooltip: "AI applies to jobs while you sleep", values: { Free: false, Basic: false, Professional: true } },
  { feature: "Priority matching", tooltip: "Your profile is boosted in employer searches", values: { Free: false, Basic: false, Professional: true } },
  { feature: "Resume tailoring", values: { Free: false, Basic: false, Professional: true } },
  { feature: "Skills assessments", values: { Free: false, Basic: false, Professional: true } },
  { feature: "Priority support", values: { Free: false, Basic: false, Professional: true } },
];

export const EMPLOYER_COMPARISON_ROWS = [
  { feature: "Job postings per month", values: { "Employer Free": "Unlimited", "Employer Basic": "Unlimited", "Employer Premium": "Unlimited" } },
  { feature: "Applicant management", values: { "Employer Free": true, "Employer Basic": true, "Employer Premium": true } },
  { feature: "Company profile", values: { "Employer Free": true, "Employer Basic": true, "Employer Premium": true } },
  { feature: "Verified badge", values: { "Employer Free": false, "Employer Basic": false, "Employer Premium": true } },
  { feature: "Candidate search", tooltip: "Search and filter talent pool", values: { "Employer Free": false, "Employer Basic": true, "Employer Premium": true } },
  { feature: "Analytics dashboard", values: { "Employer Free": false, "Employer Basic": true, "Employer Premium": true } },
  { feature: "AI candidate ranking", tooltip: "AI scores applicants against your requirements", values: { "Employer Free": false, "Employer Basic": false, "Employer Premium": true } },
  { feature: "ATS integration", values: { "Employer Free": false, "Employer Basic": false, "Employer Premium": true } },
  { feature: "API access", values: { "Employer Free": false, "Employer Basic": false, "Employer Premium": true } },
  { feature: "Priority support", values: { "Employer Free": false, "Employer Basic": false, "Employer Premium": true } },
];
